/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_NativeLib */

#ifndef _Included_app_NativeLib
#define _Included_app_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_NativeLib
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_app_NativeLib_hello
  (JNIEnv *, jobject);

/*
 * Class:     app_NativeLib
 * Method:    getRandom
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_app_NativeLib_getRandom
  (JNIEnv *, jobject);

/*
 * Class:     app_NativeLib
 * Method:    printMatrix
 * Signature: ([[F)V
 */
JNIEXPORT void JNICALL Java_app_NativeLib_printMatrix
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     app_NativeLib
 * Method:    processObject
 * Signature: (Lapp/MyObject;)Lapp/MyObject;
 */
JNIEXPORT jobject JNICALL Java_app_NativeLib_processObject
  (JNIEnv *, jobject, jobject);

/*
 * Class:     app_NativeLib
 * Method:    processList
 * Signature: (Ljava/util/List;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_app_NativeLib_processList
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
